[package]
name = "syrusakbary/astro-static-site-15e"
version = "0.1.0"
description = "wasmer-tests/wasmer-edge-astro-sample website"
repository = "https://github.com/syrusakbary/astro-static-site-15e"

[dependencies]
"wasmer/static-web-server" = "*"

[fs]
public = "dist"
